# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af1a54b6a00eed7280771e061339ea87657e939e86ef9f4d24cdf8a820065be97894a3c330c5fb5b3a21b01f654c95f2d118d8146f99875eb78b65cb0ee2037a

test:
  secret_key_base: d281aabbc0b4f8c6e7f219fcf0a09500acf7e36f348f777b611792de692c0327205cd9569adbb6c3c08b633dc05953effb83fff736c4b2c21ba380192b5ec506

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
